import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import { Archivo } from "next/font/google";
import "./globals.css";
import { Navbar } from "./homeSections/Navbar";
import { Footer } from "./homeSections/Footer";
import { images } from "@/constants/images";
import { buttons } from "@/constants/buttons";
import { Links } from "@/constants/links";
import { ThemeProvider } from "@/components/dark-mode/theme-provider";
import { ModeToggle } from "@/components/dark-mode/toggle";

const inter = Archivo({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-black bg-bg2 no-scrollbar`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar logo={images.logo} button={buttons[1]} navLinks={Links} />
          {children}
          <ModeToggle />
          <Footer button={buttons[4]} logo={images.logo} columnLinks={Links} />
        </ThemeProvider>
      </body>
    </html>
  );
}
