import type { Metadata } from "next";
import { Archivo } from "next/font/google";
import "./globals.css";
import { Navbar } from "./homeSections/Navbar";
import { Footer } from "./homeSections/Footer";
import { images } from "@/constants/images";
import { buttons } from "@/constants/buttons";
import { Links } from "@/constants/links";
import { ThemeProvider } from "@/components/dark-mode/theme-provider";
import { ModeToggle } from "@/components/dark-mode/toggle";
import {
  IubendaProvider,
  IubendaCookieSolutionBannerConfigInterface,
} from "@mep-agency/next-iubenda";

const inter = Archivo({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const iubendaBannerConfig: IubendaCookieSolutionBannerConfigInterface = {
  siteId: 3822715, // Your site ID
  cookiePolicyId: 94168299, // Your cookie policy ID
  lang: "it",
  floatingPreferencesButtonDisplay: "bottom-left",

  // See https://www.iubenda.com/en/help/1205-how-to-configure-your-cookie-solution-advanced-guide
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-black bg-bg2 no-scrollbar`}>
        <IubendaProvider bannerConfig={iubendaBannerConfig}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar logo={images.logo} button={buttons[1]} navLinks={Links} />
            {children}
            {<ModeToggle />}
            <Footer
              button={buttons[4]}
              logo={images.logo}
              columnLinks={Links}
            />
          </ThemeProvider>
        </IubendaProvider>
      </body>
    </html>
  );
}
